osx_image: xcode9
rvm:
  - 2.2.2
language: objective-c
before_install: 
  - gem install cocoapods
  - pod repo update
  - gem install xcpretty slather -N
  - xcrun instruments -w "iPhone 6 (11.0)" || echo "(Pre)Launched the simulator."
cache: cocoapods
podfile: Example/Podfile
script:
  - set -o pipefail && xcodebuild test -workspace example/RPCircularProgressExample.xcworkspace -scheme "RPCircularProgressExample" -destination "platform=iOS Simulator,name=iPhone 6,OS=11.0" -enableCodeCoverage YES ONLY_ACTIVE_ARCH=YES | xcpretty -c
after_success:
  - pod lib lint --allow-warnings
  - slather coverage --ignore "../**/*/Xcode*" --scheme "RPCircularProgressExample" --workspace example/RPCircularProgressExample.xcworkspace example/RPCircularProgressExample.xcodeproj